---
title: "Measures of Dispersion"
author: "Arif_Furkan"
date: "2024-06-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Showing the basic features of the data with the Stargazer package

```{r}
library(stargazer)
data(mtcars)
stargazer(mtcars,type = "text",median = TRUE,iqr = TRUE)
```

# Checking central tendency measures with the Psych package

```{r}
library(psych)
with(mtcars, c(mean(mpg),sd(mpg),median(mpg),geometric.mean(mpg),range(mpg)))
with(mtcars, c(IQR(mpg),quantile(mpg)))
mid.range <- with(mtcars, 0.5*(min(mpg) + max(mpg)))
mid.range
```

# Calculation of distribution criteria with the mad function

```{r}
with(mtcars, c(var(mpg),sd(mpg),(100*sd(mpg)/mean(mpg))))
meanAD <- mad(mtcars$mpg, center = mean(mtcars$mpg))
medianAD <- mad(mtcars$mpg)
meanAD
medianAD
```

# Correlation Test

```{r, fig.width=7, fig.height=4}
cor_result <- cor.test(mtcars$mpg, mtcars$hp)
cor_result
require(ggplot2)
ggplot(mtcars, aes(x = mpg, y = hp)) +
geom_point() +
geom_smooth(method = "lm", se = FALSE) +
labs(x = "Miles per Gallon (mpg)", y = "Horsepower (hp)", title = "Correlation Between mpg and hp")
```

# Partial Correlation

```{r}
require(ppcor)
attach(mtcars)
pcor.test(mpg,hp,wt)
require(psych)
with(mtcars, c(cor(mpg,hp),cov(mpg,hp)))
skewness <- skew(mtcars$mpg)
kurtosis <- kurtosi(mtcars$mpg)
c(skewness,kurtosis)
```

# Kurtosis Chart

```{r, fig.width=7, fig.height=3}
library(e1071)
curve(dnorm(x, mean = mean(mtcars$mpg), sd = sd(mtcars$mpg)),
from = min(mtcars$mpg), to = max(mtcars$mpg),
xlab = "Miles per Gallon (mpg)", ylab = "Density",
main = "Kurtosis Graph")
lines(density(mtcars$mpg), col = "blue")
```

# Skewness Chart

```{r, fig.width=7, fig.height=3}
skewness <- skewness(mtcars$mpg)
curve(dnorm(x, mean = mean(mtcars$mpg), sd = sd(mtcars$mpg)),
from = min(mtcars$mpg), to = max(mtcars$mpg),
xlab = "Miles per Gallon (mpg)", ylab = "Density",
main = paste("Skewness:", round(skewness, 2)))
lines(density(mtcars$mpg), col = "blue")
abline(v = mean(mtcars$mpg), col = "red", lty = 2)
legend("topright", legend = c("Normal distribution", "Data Density", "Mean"),
col = c("black", "blue", "red"), lty = c(1, 1, 2), cex = 0.8)
```
